'use client';
import { ComposableMap, Geographies, Geography, Marker } from 'react-simple-maps';
const GEO_URL = 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json';
const coords: Record<string, [number, number]> = { US: [-98, 39], USA: [-98, 39], UnitedStates: [-98, 39], Canada: [-106, 56], CA: [-106, 56], UnitedKingdom: [-2, 54], UK: [-2, 54], GB: [-2, 54], Germany: [10, 51], DE: [10, 51], France: [2, 46], FR: [2, 46], Italy: [12, 43], IT: [12, 43], Spain: [-4, 40], ES: [-4, 40], India: [78, 21], IN: [78, 21], Australia: [133, -25], AU: [133, -25], Brazil: [-51, -10], BR: [-51, -10], Japan: [138, 37], JP: [138, 37], China: [104, 35], CN: [104, 35] };
function key(s: string) { return s.replace(/[^a-zA-Z]/g, ''); }
export function ThreatMap({ byCountry }: { byCountry: Record<string, number> }) {
  const markers = Object.entries(byCountry).map(([country, count]) => ({ country, count, xy: coords[country] ?? coords[key(country)] })).filter((m) => m.xy) as {country:string; count:number; xy:[number,number]}[];
  return <section className="panel h-full p-5"><h2 className="mono mb-5 border-b hairline pb-3 text-xs uppercase tracking-[.22em] text-[#39ff7a]">Geographic threat origin</h2><ComposableMap projectionConfig={{ scale: 118 }} className="h-[265px] w-full"><Geographies geography={GEO_URL}>{({ geographies }) => geographies.map((geo) => <Geography key={geo.rsmKey} geography={geo} fill="#151b20" stroke="rgba(255,255,255,.08)" strokeWidth={.4} style={{ default: { outline: 'none' }, hover: { outline: 'none', fill: '#1b2429' }, pressed: { outline: 'none' } }} />)}</Geographies>{markers.map((m) => <Marker key={m.country} coordinates={m.xy}><circle r={Math.min(10, 3 + m.count * 2)} fill="#39ff7a" opacity="0.68" /><circle r={Math.min(18, 7 + m.count * 3)} fill="none" stroke="#39ff7a" opacity="0.18" /></Marker>)}</ComposableMap><div className="mono mt-3 grid grid-cols-2 gap-2 text-[10px] uppercase text-[#5a6571]">{markers.slice(0,4).map(m => <span key={m.country}>{m.country}: <b className="text-[#e6edf3]">{m.count}</b></span>)}</div></section>;
}
